### ISSUE TITLE
Boots with devtools open

### ISSUE THREAD

**Issue by tmpvar** [joemccann/npm-search-bar#2]
<img width="357" alt="screen shot 2016-10-11 at 11 52 34 am" src="https://cloud.githubusercontent.com/assets/46673/19277881/43a3bc7c-8fa9-11e6-8951-87ff9d384ff3.png">

And the normal COMMAND+OPTION+J does not close them

**Comment by joemccann** [comment]
Derp. Just need to recomment in `main.js`
